Repository SereinMC/Serein, pull requests merged in 2023-02, with the labels that each got.

#47 fix: ignore initials when asking
  index.js
Labels: quickly-approve

#48 build: update to 1.1.9
  index.js
  package.json
Labels: quickly-approve

#51 docs: fix wrong command in `README.md`
  README.md
Labels: fast-approve

#57 fix: filp issue about `askYes`
  index.js
  package.json
  utils.js
Labels: fast-approve, publish

#58 ci: support test on node nightly
  .github/workflows/test-on-linux-node-nightly.yml
Labels: fast-approve

#59 ci: fix test on node nightly workflow
  .github/workflows/test-on-linux-node-nightly.yml
Labels: fast-approve

#60 ci: new `publish-npm` workflow
  .github/workflows/npm-publish.yml
Labels: fast-approve

#61 ci: fix error node version in `npm-publish` workflow
  .github/workflows/npm-publish.yml
Labels: fast-approve

#62 ci: remove error dependency in `npm-publish
  .github/workflows/npm-publish.yml
Labels: fast-approve

#64 build: update .npmignore
  .npmignore
Labels: fast-approve
